language: python
python:
  - "2.7"
script: nosetests
secure: "KhHqvJsiWYMlinnsDxf/Yyo5jzzEImXq2p/XW3uhHTJDakUCErbo5laT0slaEvrUP9nykmCJa4pAktLuCA6Z6H4ABiVtunoCDi8RFbYYvw+E8wwsrLnWg103U38xYeoUxmDJbf2WWLMZytz80jDVpvoL9wdWie3a4vqhKLix8j8="
